// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: multipaxos.proto

package proto

import (
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_multipaxos_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val string `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_multipaxos_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error bool `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_multipaxos_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

type PrepareMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rnd  uint32 `protobuf:"varint,1,opt,name=rnd,proto3" json:"rnd,omitempty"`
	Slot uint32 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *PrepareMsg) Reset() {
	*x = PrepareMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMsg) ProtoMessage() {}

func (x *PrepareMsg) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMsg.ProtoReflect.Descriptor instead.
func (*PrepareMsg) Descriptor() ([]byte, []int) {
	return file_multipaxos_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareMsg) GetRnd() uint32 {
	if x != nil {
		return x.Rnd
	}
	return 0
}

func (x *PrepareMsg) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type PromiseSlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot  uint32 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Rnd   uint32 `protobuf:"varint,2,opt,name=rnd,proto3" json:"rnd,omitempty"`
	Value *Value `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	Final bool   `protobuf:"varint,4,opt,name=final,proto3" json:"final,omitempty"`
}

func (x *PromiseSlot) Reset() {
	*x = PromiseSlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromiseSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseSlot) ProtoMessage() {}

func (x *PromiseSlot) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseSlot.ProtoReflect.Descriptor instead.
func (*PromiseSlot) Descriptor() ([]byte, []int) {
	return file_multipaxos_proto_rawDescGZIP(), []int{4}
}

func (x *PromiseSlot) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *PromiseSlot) GetRnd() uint32 {
	if x != nil {
		return x.Rnd
	}
	return 0
}

func (x *PromiseSlot) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PromiseSlot) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

// PromiseMsg is the reply from an Acceptor to the Proposer in response to a PrepareMsg.
// The Acceptor will only respond if the PrepareMsg.rnd > Acceptor.rnd.
type PromiseMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rnd      uint32         `protobuf:"varint,1,opt,name=rnd,proto3" json:"rnd,omitempty"`
	Slots    []*PromiseSlot `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty"`
	FromNode uint32         `protobuf:"varint,3,opt,name=fromNode,proto3" json:"fromNode,omitempty"`
}

func (x *PromiseMsg) Reset() {
	*x = PromiseMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromiseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseMsg) ProtoMessage() {}

func (x *PromiseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseMsg.ProtoReflect.Descriptor instead.
func (*PromiseMsg) Descriptor() ([]byte, []int) {
	return file_multipaxos_proto_rawDescGZIP(), []int{5}
}

func (x *PromiseMsg) GetRnd() uint32 {
	if x != nil {
		return x.Rnd
	}
	return 0
}

func (x *PromiseMsg) GetSlots() []*PromiseSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *PromiseMsg) GetFromNode() uint32 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

// AcceptMsg is sent by the Proposer, asking the Acceptors to lock-in the value, val.
// If AcceptMsg.rnd < Acceptor.rnd, the message will be ignored.
type AcceptMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rnd  uint32 `protobuf:"varint,1,opt,name=rnd,proto3" json:"rnd,omitempty"`
	Slot uint32 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Val  *Value `protobuf:"bytes,3,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *AcceptMsg) Reset() {
	*x = AcceptMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMsg) ProtoMessage() {}

func (x *AcceptMsg) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMsg.ProtoReflect.Descriptor instead.
func (*AcceptMsg) Descriptor() ([]byte, []int) {
	return file_multipaxos_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptMsg) GetRnd() uint32 {
	if x != nil {
		return x.Rnd
	}
	return 0
}

func (x *AcceptMsg) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *AcceptMsg) GetVal() *Value {
	if x != nil {
		return x.Val
	}
	return nil
}

// LearnMsg is sent by an Acceptor to the Proposer, if the Acceptor agreed to lock-in the value, val.
// The LearnMsg is also sent by the Proposer in a Commit.
type LearnMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rnd      uint32 `protobuf:"varint,1,opt,name=rnd,proto3" json:"rnd,omitempty"`
	Val      *Value `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	Slot     uint32 `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	FromNode uint32 `protobuf:"varint,4,opt,name=fromNode,proto3" json:"fromNode,omitempty"`
}

func (x *LearnMsg) Reset() {
	*x = LearnMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LearnMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnMsg) ProtoMessage() {}

func (x *LearnMsg) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnMsg.ProtoReflect.Descriptor instead.
func (*LearnMsg) Descriptor() ([]byte, []int) {
	return file_multipaxos_proto_rawDescGZIP(), []int{7}
}

func (x *LearnMsg) GetRnd() uint32 {
	if x != nil {
		return x.Rnd
	}
	return 0
}

func (x *LearnMsg) GetVal() *Value {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *LearnMsg) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *LearnMsg) GetFromNode() uint32 {
	if x != nil {
		return x.FromNode
	}
	return 0
}

// DecidedValue is sent by an Acceptor to the Learner
type DecidedValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot uint32 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Val  *Value `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *DecidedValue) Reset() {
	*x = DecidedValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecidedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecidedValue) ProtoMessage() {}

func (x *DecidedValue) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecidedValue.ProtoReflect.Descriptor instead.
func (*DecidedValue) Descriptor() ([]byte, []int) {
	return file_multipaxos_proto_rawDescGZIP(), []int{8}
}

func (x *DecidedValue) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *DecidedValue) GetVal() *Value {
	if x != nil {
		return x.Val
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxos_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxos_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_multipaxos_proto_rawDescGZIP(), []int{9}
}

var File_multipaxos_proto protoreflect.FileDescriptor

var file_multipaxos_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x67, 0x6f, 0x72, 0x75, 0x6d,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22,
	0x20, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x32, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4d, 0x73, 0x67, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x6e,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x6d, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65,
	0x53, 0x6c, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66,
	0x69, 0x6e, 0x61, 0x6c, 0x22, 0x64, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x4d,
	0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x72, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x6d,
	0x69, 0x73, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x51, 0x0a, 0x09, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x1e, 0x0a,
	0x03, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x6c, 0x0a,
	0x08, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x03, 0x76,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6c, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x42, 0x0a, 0x0c, 0x44,
	0x65, 0x63, 0x69, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12,
	0x1e, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xfd, 0x01, 0x0a, 0x0a, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x50, 0x61, 0x78, 0x6f, 0x73, 0x12, 0x2c, 0x0a, 0x05, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x04, 0xb0, 0xb5, 0x18, 0x01, 0x12, 0x35, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x4d, 0x73, 0x67, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x6d,
	0x69, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x22, 0x04, 0xa0, 0xb5, 0x18, 0x01, 0x12, 0x2e, 0x0a, 0x06,
	0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x90, 0xb8, 0x18, 0x01, 0x12, 0x2c, 0x0a, 0x05,
	0x4c, 0x65, 0x61, 0x72, 0x6e, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x65,
	0x61, 0x72, 0x6e, 0x4d, 0x73, 0x67, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x90, 0xb8, 0x18, 0x01, 0x12, 0x2c, 0x0a, 0x04, 0x50, 0x69,
	0x6e, 0x67, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x04, 0x98, 0xb5, 0x18, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x61, 0x78, 0x6f,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_multipaxos_proto_rawDescOnce sync.Once
	file_multipaxos_proto_rawDescData = file_multipaxos_proto_rawDesc
)

func file_multipaxos_proto_rawDescGZIP() []byte {
	file_multipaxos_proto_rawDescOnce.Do(func() {
		file_multipaxos_proto_rawDescData = protoimpl.X.CompressGZIP(file_multipaxos_proto_rawDescData)
	})
	return file_multipaxos_proto_rawDescData
}

var file_multipaxos_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_multipaxos_proto_goTypes = []interface{}{
	(*Heartbeat)(nil),    // 0: proto.Heartbeat
	(*Value)(nil),        // 1: proto.Value
	(*Response)(nil),     // 2: proto.Response
	(*PrepareMsg)(nil),   // 3: proto.PrepareMsg
	(*PromiseSlot)(nil),  // 4: proto.PromiseSlot
	(*PromiseMsg)(nil),   // 5: proto.PromiseMsg
	(*AcceptMsg)(nil),    // 6: proto.AcceptMsg
	(*LearnMsg)(nil),     // 7: proto.LearnMsg
	(*DecidedValue)(nil), // 8: proto.DecidedValue
	(*Empty)(nil),        // 9: proto.Empty
}
var file_multipaxos_proto_depIdxs = []int32{
	1,  // 0: proto.PromiseSlot.Value:type_name -> proto.Value
	4,  // 1: proto.PromiseMsg.slots:type_name -> proto.PromiseSlot
	1,  // 2: proto.AcceptMsg.val:type_name -> proto.Value
	1,  // 3: proto.LearnMsg.val:type_name -> proto.Value
	1,  // 4: proto.DecidedValue.val:type_name -> proto.Value
	1,  // 5: proto.MultiPaxos.Write:input_type -> proto.Value
	3,  // 6: proto.MultiPaxos.Prepare:input_type -> proto.PrepareMsg
	6,  // 7: proto.MultiPaxos.Accept:input_type -> proto.AcceptMsg
	7,  // 8: proto.MultiPaxos.Learn:input_type -> proto.LearnMsg
	0,  // 9: proto.MultiPaxos.Ping:input_type -> proto.Heartbeat
	2,  // 10: proto.MultiPaxos.Write:output_type -> proto.Response
	5,  // 11: proto.MultiPaxos.Prepare:output_type -> proto.PromiseMsg
	9,  // 12: proto.MultiPaxos.Accept:output_type -> proto.Empty
	9,  // 13: proto.MultiPaxos.Learn:output_type -> proto.Empty
	9,  // 14: proto.MultiPaxos.Ping:output_type -> proto.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_multipaxos_proto_init() }
func file_multipaxos_proto_init() {
	if File_multipaxos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_multipaxos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromiseSlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromiseMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxos_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LearnMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxos_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecidedValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxos_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_multipaxos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_multipaxos_proto_goTypes,
		DependencyIndexes: file_multipaxos_proto_depIdxs,
		MessageInfos:      file_multipaxos_proto_msgTypes,
	}.Build()
	File_multipaxos_proto = out.File
	file_multipaxos_proto_rawDesc = nil
	file_multipaxos_proto_goTypes = nil
	file_multipaxos_proto_depIdxs = nil
}
