version: "3.9"
services:
  node1:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ID=0
    networks:
      - distributedleader
  node2:
    build: .
    ports:
      - "5001:8080"
    environment:
      - ID=1
    networks:
      - distributedleader
  node3:
    build: .
    ports:
      - "5002:8080"
    environment:
      - ID=2
    networks:
      - distributedleader
  node4:
    build: .
    ports:
      - "5003:8080"
    environment:
      - ID=3
    networks:
      - distributedleader

networks:
  distributedleader:
    driver: bridge