version: "3.9"
services:
  node1:
    build: .
    ports:
      - "5000:8080"
    networks:
      - storage
  node2:
    build: .
    ports:
      - "5001:8080"
    networks:
      - storage
  node3:
    build: .
    ports:
      - "5002:8080"
    networks:
      - storage
  node4:
    build: .
    ports:
      - "5003:8080"
    networks:
      - storage

networks:
  storage:
    driver: bridge