# syntax=docker/dockerfile:1

FROM golang:alpine

WORKDIR /app

COPY gorums gorums
COPY src/go.mod .
COPY src/go.sum .
RUN go mod download

COPY src/. .

RUN CGO_ENABLED=0 GOOS=linux go build -o /server

ENV PRODUCTION=1
ENV SERVER=1

CMD [ "/server" ]