version: "3.9"
services:
  srv1:
    build: 
      context: .
      dockerfile: Master/benchmarks/Dockerfile.Server
    environment:
      - ID=0
      - SERVER=1
      - CONF=${CONF}
      - PRODUCTION=${PRODUCTION}
      - BENCH=${BENCH}
      - LOG=${LOG}
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    networks:
      MasterLab:
        ipv4_address: 10.0.0.5
  srv2:
    build: 
      context: .
      dockerfile: Master/benchmarks/Dockerfile.Server
    environment:
      - ID=1
      - SERVER=1
      - CONF=${CONF}
      - PRODUCTION=${PRODUCTION}
      - BENCH=${BENCH}
      - LOG=${LOG}
    ports:
      - "5001:5001"
    volumes:
      - ./logs:/app/logs
    networks:
      MasterLab:
        ipv4_address: 10.0.0.6
  srv3:
    build: 
      context: .
      dockerfile: Master/benchmarks/Dockerfile.Server
    environment:
      - ID=2
      - SERVER=1
      - CONF=${CONF}
      - PRODUCTION=${PRODUCTION}
      - BENCH=${BENCH}
      - LOG=${LOG}
    ports:
      - "5002:5002"
    volumes:
      - ./logs:/app/logs
    networks:
      MasterLab:
        ipv4_address: 10.0.0.7
  srv4:
    build: 
      context: .
      dockerfile: Master/benchmarks/Dockerfile.Server
    environment:
      - ID=3
      - SERVER=1
      - CONF=${CONF}
      - PRODUCTION=${PRODUCTION}
      - BENCH=${BENCH}
      - LOG=${LOG}
    ports:
      - "5003:5003"
    volumes:
      - ./logs:/app/logs
    networks:
      MasterLab:
        ipv4_address: 10.0.0.8
  srv5:
    build: 
      context: .
      dockerfile: Master/benchmarks/Dockerfile.Server
    environment:
      - ID=4
      - SERVER=1
      - CONF=${CONF}
      - PRODUCTION=${PRODUCTION}
      - BENCH=${BENCH}
      - LOG=${LOG}
    ports:
      - "5004:5004"
    volumes:
      - ./logs:/app/logs
    networks:
      MasterLab:
        ipv4_address: 10.0.0.9
  srv6:
    build: 
      context: .
      dockerfile: Master/benchmarks/Dockerfile.Server
    environment:
      - ID=5
      - SERVER=1
      - CONF=${CONF}
      - PRODUCTION=${PRODUCTION}
      - BENCH=${BENCH}
      - LOG=${LOG}
    ports:
      - "5005:5005"
    volumes:
      - ./logs:/app/logs
    networks:
      MasterLab:
        ipv4_address: 10.0.0.10
  srv7:
    build: 
      context: .
      dockerfile: Master/benchmarks/Dockerfile.Server
    environment:
      - ID=6
      - SERVER=1
      - CONF=${CONF}
      - PRODUCTION=${PRODUCTION}
      - BENCH=${BENCH}
      - LOG=${LOG}
    ports:
      - "5006:5006"
    volumes:
      - ./logs:/app/logs
    networks:
      MasterLab:
        ipv4_address: 10.0.0.11
  client:
    build: 
      context: .
      dockerfile: Master/benchmarks/Dockerfile.Client
    environment:
      - SERVER=0
      - CONF=${CONF}
      - PRODUCTION=${PRODUCTION}
      - BENCH=${BENCH}
      - THROUGHPUT=${THROUGHPUT}
      - STEPS=${STEPS}
      - RUNS=${RUNS}
      - DUR=${DUR}
      - LOG=${LOG}
    ports:
      - "8080-8089:8080-8089"
    volumes:
      - ./logs:/app/logs
      - ./csv:/app/csv
    networks:
      MasterLab:
        ipv4_address: 10.0.0.3
    depends_on:
      - srv1
      - srv2
      - srv3
      - srv4

networks:
  MasterLab:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
        - gateway: 10.0.0.1