version: "3.9"
services:
  srv1:
    build: 
      context: .
      dockerfile: Master/benchmarks/Dockerfile.Server
    environment:
      - PRODUCTION=1
      - BENCH=2
      - ID=0
      - SERVER=1
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    networks:
      MasterLab:
        ipv4_address: 10.0.0.5
  srv2:
    build: 
      context: .
      dockerfile: Master/benchmarks/Dockerfile.Server
    environment:
      - PRODUCTION=1
      - BENCH=2
      - ID=1
      - SERVER=1
    ports:
      - "5001:5001"
    volumes:
      - ./logs:/app/logs
    networks:
      MasterLab:
        ipv4_address: 10.0.0.6
  srv3:
    build: 
      context: .
      dockerfile: Master/benchmarks/Dockerfile.Server
    environment:
      - PRODUCTION=1
      - BENCH=2
      - ID=2
      - SERVER=1
    ports:
      - "5002:5002"
    volumes:
      - ./logs:/app/logs
    networks:
      MasterLab:
        ipv4_address: 10.0.0.7
  client:
    build: 
      context: .
      dockerfile: Master/benchmarks/Dockerfile.Client
    environment:
      - PRODUCTION=1
      - BENCH=2
      - SERVER=0
      - THROUGHPUT=5000
      - STEPS=10
      - DUR=10
    ports:
      - "8080-8089:8080-8089"
    volumes:
      - ./logs:/app/logs
      - ./csv:/app/csv
    networks:
      MasterLab:
        ipv4_address: 10.0.0.3
    depends_on:
      - srv1
      - srv2
      - srv3

networks:
  MasterLab:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
        - gateway: 10.0.0.1